FROM docker.io/library/python:3.14-slim-trixie
# Official way to get uv and uvx into the image, see https://docs.astral.sh/uv/guides/integration/docker/#installing-uv
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

# Create non-root user to increase security
RUN groupadd -g 1001 svc && \
    useradd -d /home/appuser -m -u 1001 -g svc appuser

WORKDIR /app

COPY --chown=appuser:svc src ./src
COPY --chown=appuser:svc pyproject.toml Makefile uv.lock src/importer/README.md ./

# Install dependencies (clean cache, upgrade packages)
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y make && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    uv sync --locked --no-dev && \
    chown -R appuser:svc .

# Switch to non-root user
USER appuser

CMD make download-and-bootstrap-data
