[project]
name = "ru_budget_tracker"
version = "0.1.0"
description = """A dashboard application for Stiftung Wissenschaft und Politik (SWP).
Dashboard provides insights into budgets and expenditures of the russion government.
Includes military spending and Classified Spending."""
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiosqlite>=0.21.0",
    "alembic>=1.17.1",
    "pandas>=3.0.0",
    "gunicorn>=23.0.0",
    "networkx>=3.5",
    "plotly>=6.6.0",
    "pydantic>=2.12.3",
    "pydantic-settings>=2.11.0",
    "sqlalchemy>=2.0.44",
    "openpyxl>=3.1.5",
    "xlrd>=2.0.2",
    "deepl>=1.18.0",
    "requests>=2.32.5",
    "dash-bootstrap-components>=2.0.4",
    "dash>=4.1.0",
    "httpx2>=2.4.0",
]

[dependency-groups]
dev = [
    "nbformat>=5.10.4",
    "faker>=37.12.0",
    "pytest>=8.4.0",
    "types-python-dateutil>=2.9.0",
    "types-requests>=2.32.0",
    "mypy>=2.1.0",
]

[tool.uv]
package = false

# Ruff settings
[tool.ruff]
# Configuration for Ruff
# Include the following rules:
# - Line length of 100 characters
# - T20: print() and pprint() should not be used in production code
line-length = 100
lint.select = ["T20"]

[tool.ty.environment]
root = ["./src"]

[tool.mypy]
python_version = "3.13"
explicit_package_bases = true
mypy_path = "src"

[[tool.mypy.overrides]]
module = [
    "dateutil.*",
    "requests.*",
    "dash.*",
    "dash_bootstrap_components.*",
    "plotly.*",
    "alembic.*",
    "openai.*",
    "pandas.*",
    "networkx.*",
    "openpyxl.*",
    "xlrd.*",
    "aiosqlite.*",
]
ignore_missing_imports = true
