"""initial setup

Revision ID: 0001
Revises:
Create Date: 2025-11-11 20:29:58.216379

"""

from alembic import op
import sqlalchemy as sa
from database import get_sync_session  # noqa: F401


# revision identifiers, used by Alembic.
revision = "0001"  # pragma: allowlist secret
down_revision = None  # pragma: allowlist secret
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "budgets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("original_identifier", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("name_translated", sa.String(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("description_translated", sa.Text(), nullable=True),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("scope", sa.String(), nullable=True),
        sa.Column("published_at", sa.Date(), nullable=False),
        sa.Column("planned_at", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_budgets_original_identifier"), "budgets", ["original_identifier"], unique=False
    )
    op.create_table(
        "conversion_rates",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("started_at", sa.Date(), nullable=True),
        sa.Column("ended_at", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "dimensions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("original_identifier", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("name_translated", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["parent_id"], ["dimensions.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_dimensions_original_identifier"),
        "dimensions",
        ["original_identifier"],
        unique=True,
    )
    op.create_table(
        "expenses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("budget_id", sa.Integer(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["budget_id"], ["budgets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "association_table",
        sa.Column("expense_id", sa.Integer(), nullable=True),
        sa.Column("dimension_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["dimension_id"],
            ["dimensions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["expense_id"],
            ["expenses.id"],
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("association_table")
    op.drop_table("expenses")
    op.drop_index(op.f("ix_dimensions_original_identifier"), table_name="dimensions")
    op.drop_table("dimensions")
    op.drop_table("conversion_rates")
    op.drop_index(op.f("ix_budgets_original_identifier"), table_name="budgets")
    op.drop_table("budgets")
    # ### end Alembic commands ###
