"""update unique constraint dimension

Revision ID: 0002
Revises: 0001
Create Date: 2025-11-21 10:20:08.646887

"""

from alembic import op
import sqlalchemy as sa  # noqa: F401
from database import get_sync_session  # noqa: F401


# Revision identifiers, used by Alembic for version tracking
revision = "0002"  # pragma: allowlist secret
down_revision = "0001"  # pragma: allowlist secret
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("dimensions") as batch_op:
        batch_op.drop_index(op.f("ix_dimensions_original_identifier"))
        batch_op.create_unique_constraint(
            "uix_dimensions_name_type_original_parent",
            ["name", "type", "original_identifier", "parent_id"],
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("dimensions") as batch_op:
        batch_op.drop_constraint("uix_dimensions_name_type_original_parent", type_="unique")
        batch_op.create_index(
            op.f("ix_dimensions_original_identifier"),
            ["original_identifier"],
            unique=True,
        )
    # ### end Alembic commands ###