"""update unique constraint dimension

Revision ID: 0002
Revises: 0001
Create Date: 2025-11-21 10:20:08.646887

"""

from alembic import op
import sqlalchemy as sa
from database import get_sync_session  # noqa: F401


# revision identifiers, used by Alembic.
revision = "0002"  # pragma: allowlist secret
down_revision = "0001"  # pragma: allowlist secret
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_dimensions_original_identifier"), table_name="dimensions")
    op.create_unique_constraint(
        "uix_dimensions_name_type_original_parent",
        "dimensions",
        ["name", "type", "original_identifier", "parent_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uix_dimensions_name_type_original_parent", "dimensions", type_="unique")
    op.create_index(
        op.f("ix_dimensions_original_identifier"), "dimensions", ["original_identifier"], unique=1
    )
    # ### end Alembic commands ###
