"""add indexes

Revision ID: 0003
Revises: 0002
Create Date: 2026-02-16 12:14:19.342500

"""

from alembic import op
import sqlalchemy as sa
from database import get_sync_session  # noqa: F401


# revision identifiers, used by Alembic.
revision = "0003"  # pragma: allowlist secret
down_revision = "0002"  # pragma: allowlist secret
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_assoc_expense_dimension",
        "association_table",
        ["expense_id", "dimension_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_association_table_dimension_id"),
        "association_table",
        ["dimension_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_association_table_expense_id"), "association_table", ["expense_id"], unique=False
    )
    op.create_index(op.f("ix_budgets_published_at"), "budgets", ["published_at"], unique=False)
    op.create_index(op.f("ix_budgets_type"), "budgets", ["type"], unique=False)
    op.create_index(op.f("ix_dimensions_parent_id"), "dimensions", ["parent_id"], unique=False)
    op.create_index(op.f("ix_expenses_budget_id"), "expenses", ["budget_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_expenses_budget_id"), table_name="expenses")
    op.drop_index(op.f("ix_dimensions_parent_id"), table_name="dimensions")
    op.drop_index(op.f("ix_budgets_type"), table_name="budgets")
    op.drop_index(op.f("ix_budgets_published_at"), table_name="budgets")
    op.drop_index(op.f("ix_association_table_expense_id"), table_name="association_table")
    op.drop_index(op.f("ix_association_table_dimension_id"), table_name="association_table")
    op.drop_index("ix_assoc_expense_dimension", table_name="association_table")
    # ### end Alembic commands ###
