"""change dimension unique constraint to composite

Revision ID: 2ad7ff7d9ff8
Revises: fb88575a7e86
Create Date: 2025-11-13 18:19:18.501381

"""
from alembic import op
import sqlalchemy as sa
from database import get_sync_session  # noqa: F401


# revision identifiers, used by Alembic.
revision = '2ad7ff7d9ff8'  # pragma: allowlist secret
down_revision = 'fb88575a7e86'  # pragma: allowlist secret
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dimensions', schema=None) as batch_op:
        # Remove old unique constraint
        batch_op.drop_constraint('uq_dimensions_original_identifier', type_='unique')
        # Add new composite unique constraint
        batch_op.create_unique_constraint(
            'uix_budget_type_identifier',
            ['budget_id', 'type', 'original_identifier']
        )

def downgrade() -> None:
    with op.batch_alter_table('dimensions', schema=None) as batch_op:
        batch_op.drop_constraint('uix_budget_type_identifier', type_='unique')
        batch_op.create_unique_constraint(
            'uq_dimensions_original_identifier',
            ['original_identifier']
        )