"""change dimension unique constraint to composite - remove unique from dimensions.original_identifier

Revision ID: 7f4d8a31543d
Revises: 2ad7ff7d9ff8
Create Date: 2025-11-13 20:15:55.464611

"""
from alembic import op
import sqlalchemy as sa
from database import get_sync_session  # noqa: F401


# revision identifiers, used by Alembic.
revision = '7f4d8a31543d'  # pragma: allowlist secret
down_revision = '2ad7ff7d9ff8'  # pragma: allowlist secret
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dimensions_original_identifier'), table_name='dimensions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_dimensions_original_identifier'), 'dimensions', ['original_identifier'], unique=1)
    # ### end Alembic commands ###
