"""add_budget_id_to_dimensions

Revision ID: dd9af3d85bf8
Revises: 0001
Create Date: 2025-11-13 16:58:58.504591

"""
from alembic import op
import sqlalchemy as sa
from database import get_sync_session  # noqa: F401


# revision identifiers, used by Alembic.
revision = 'dd9af3d85bf8'  # pragma: allowlist secret
down_revision = '0001'  # pragma: allowlist secret
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dimensions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('budget_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_dimensions_budget_id', 'budgets', ['budget_id'], ['id'], ondelete='CASCADE')
        batch_op.create_unique_constraint('uq_dimensions_original_identifier', ['original_identifier'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dimensions', schema=None) as batch_op:
        batch_op.drop_constraint('uq_dimensions_original_identifier', type_='unique')
        batch_op.drop_constraint('fk_dimensions_budget_id', type_='foreignkey')
        batch_op.drop_column('budget_id')
    # ### end Alembic commands ###
