"""add dimensions relationship to budget

Revision ID: fb88575a7e86
Revises: dd9af3d85bf8
Create Date: 2025-11-13 17:39:24.094015

"""
from alembic import op
import sqlalchemy as sa
from database import get_sync_session  # noqa: F401


# revision identifiers, used by Alembic.
revision = 'fb88575a7e86'  # pragma: allowlist secret
down_revision = 'dd9af3d85bf8'  # pragma: allowlist secret
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
