name: Deployment Workflow 2

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  # changes:
  #   runs-on: ubuntu-latest
  #   outputs:
  #     app:      ${{ steps.filter.outputs.app }}
  #     importer: ${{ steps.filter.outputs.importer }}
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: dorny/paths-filter@v3
  #       id: filter
  #       with:
  #         filters: |
  #           app:
  #             - "./**"
  #             - "!./importer/**"
  #           importer:
  #             - "./importer/**"

  build-app:
    # needs: changes
    # if: needs.changes.outputs.app == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@b9e0990d219a03df7633c93f6f005a8fecbcab22 #v7.0.0
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@020b7354dd55a28effcab0f3b19639fe24d3f58b #v6.1.0
        with:
          images: ghcr.io/${{ github.repository }}/app
          tags: |
            type=sha
      - uses: docker/login-action@3864d6aed8ff134b2ed894ce00c87695c709c870 #v4.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@ff26911fd365b0233252dfbd8eede1c0e9ef9a51 #v7.2.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  build-importer:
    # needs: changes
    # if: needs.changes.outputs.importer == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@b9e0990d219a03df7633c93f6f005a8fecbcab22 #v7.0.0
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@020b7354dd55a28effcab0f3b19639fe24d3f58b #v6.1.0
        with:
          images: ghcr.io/${{ github.repository }}/importer
          tags: |
            type=sha
      - uses: docker/login-action@3864d6aed8ff134b2ed894ce00c87695c709c870 #v4.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@ff26911fd365b0233252dfbd8eede1c0e9ef9a51 #v7.2.0
        with:
          context: ./importer
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  
